FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements.txt
COPY ./requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the application code
COPY ./webservice.py /app/webservice.py
COPY ./core.py /app/core.py

# Expose port 9000
EXPOSE 9000

# Set environment variables
ENV ASR_MODEL="turbo"
ENV ASR_ENGINE="openai_whisper"

# Run the application
CMD ["uvicorn", "webservice:app", "--host", "0.0.0.0", "--port", "9000"]
