name: lyricsenv
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.9
  - pytorch
  - fastapi
  - uvicorn[standard]
  - numpy
  - ffmpeg-python
  - scipy
  - python-dotenv
pip:
  - openai-whisper
  - noisereduce
  - yt-dlp
  - librosa
  - soundfile